# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACFT
description: ACFT
baseurl: "" # the subpath of your site, e.g. /blog
email:
handle:
long_handle:

# default permalink for blog posts
permalink: blog/:title

collections:
  report-2018:
    output: true
    permalink: /report-2018/:path

# Analytics
ga_id:
inspectlet_id:

# Social handlers
twitter_url: https://twitter.com/
github_url: https://github.com/

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile', '_config.yml', 'config', '_posts', 'bin']

assets:
  features:
    automatic_img_size: false

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets
