# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alliance for Corporate Transparency
description: ACFT
baseurl: "" # the subpath of your site, e.g. /blog
email:
handle:
long_handle:

# default permalink for blog posts
permalink: news/:title

collections:
  report-2018:
    output: true
    permalink: /report-2018/:path
  static_data:
    output: true
  pages:
    permalink: /pages/:path
    output: true


# Analytics
ga_id:
inspectlet_id:

# report URLS
url_report2018: /report-2018/
companies_all: 105
companies_energy: 38
companies_health: 33
companies_ict: 34

# Social handlers
twitter_url: https://twitter.com/
github_url: https://github.com/

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile', '_config.yml', 'config', 'bin']

assets:
  features:
    automatic_img_size: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets
