# config.yml
backend:
  name: git-gateway
  repo: PopulateTools/afct-microsite
  identity_url: 'https://aftc-staging.netlify.app/.netlify/identity'
  gateway_url: 'https://aftc-staging.netlify.app/.netlify/git'
  branch: master
local_backend: true
media_folder: /assets
public_folder: /assets
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Intro', name: 'intro', widget: 'string', required: false }
      - { label: "Header Image", name: "img", widget: "image", required: false}
      - { label: "List Image", name: "img_listing", widget: "image", required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
publish_mode: editorial_workflow


